/*
 * OMDb API
 * The OMDb API is a RESTful web service to obtain movie information, all content and images on the site are contributed and maintained by our users.
 *
 * OpenAPI spec version: 1.0
 * Contact: bfritz@fadingsignal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hu.bme.aut.mobsoftlab.seriestrackerapp.network.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * EpisodeData
 */
public class EpisodeData {
    @SerializedName("Title")
    private String title = null;

    @SerializedName("Released")
    private String released = null;

    @SerializedName("Episode")
    private Integer episode = null;

    @SerializedName("imdbRating")
    private String imdbRating = null;

    @SerializedName("imdbID")
    private String imdbID = null;

    public EpisodeData title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     **/
    @ApiModelProperty(value = "")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public EpisodeData released(String released) {
        this.released = released;
        return this;
    }

    /**
     * Get released
     *
     * @return released
     **/
    @ApiModelProperty(value = "")
    public String getReleased() {
        return released;
    }

    public void setReleased(String released) {
        this.released = released;
    }

    public EpisodeData episode(Integer episode) {
        this.episode = episode;
        return this;
    }

    /**
     * Get episode
     *
     * @return episode
     **/
    @ApiModelProperty(value = "")
    public Integer getEpisode() {
        return episode;
    }

    public void setEpisode(Integer episode) {
        this.episode = episode;
    }

    public EpisodeData imdbRating(String imdbRating) {
        this.imdbRating = imdbRating;
        return this;
    }

    /**
     * Get imdbRating
     *
     * @return imdbRating
     **/
    @ApiModelProperty(value = "")
    public String getImdbRating() {
        return imdbRating;
    }

    public void setImdbRating(String imdbRating) {
        this.imdbRating = imdbRating;
    }

    public EpisodeData imdbID(String imdbID) {
        this.imdbID = imdbID;
        return this;
    }

    /**
     * Get imdbID
     *
     * @return imdbID
     **/
    @ApiModelProperty(value = "")
    public String getImdbID() {
        return imdbID;
    }

    public void setImdbID(String imdbID) {
        this.imdbID = imdbID;
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EpisodeData {\n");

        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    released: ").append(toIndentedString(released)).append("\n");
        sb.append("    episode: ").append(toIndentedString(episode)).append("\n");
        sb.append("    imdbRating: ").append(toIndentedString(imdbRating)).append("\n");
        sb.append("    imdbID: ").append(toIndentedString(imdbID)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

