/*
 * OMDb API
 * The OMDb API is a RESTful web service to obtain movie information, all content and images on the site are contributed and maintained by our users.
 *
 * OpenAPI spec version: 1.0
 * Contact: bfritz@fadingsignal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hu.bme.aut.mobsoftlab.seriestrackerapp.network.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * ModelApiResponse
 */
public class ModelApiResponse {
    @SerializedName("Response")
    private Boolean response = null;

    @SerializedName("Error")
    private String error = null;

    @SerializedName("Title")
    private String title = null;

    @SerializedName("Year")
    private String year = null;

    @SerializedName("Rated")
    private String rated = null;

    @SerializedName("Released")
    private String released = null;

    @SerializedName("Season")
    private Integer season = null;

    @SerializedName("Episode")
    private Integer episode = null;

    @SerializedName("Runtime")
    private String runtime = null;

    @SerializedName("Genre")
    private String genre = null;

    @SerializedName("Director")
    private String director = null;

    @SerializedName("Writer")
    private String writer = null;

    @SerializedName("Actors")
    private String actors = null;

    @SerializedName("Plot")
    private String plot = null;

    @SerializedName("Language")
    private String language = null;

    @SerializedName("Country")
    private String country = null;

    @SerializedName("Awards")
    private String awards = null;

    @SerializedName("Poster")
    private String poster = null;

    @SerializedName("Ratings")
    private List<RatingData> ratings = null;

    @SerializedName("Metascore")
    private String metascore = null;

    @SerializedName("imdbRating")
    private String imdbRating = null;

    @SerializedName("imdbVotes")
    private String imdbVotes = null;

    @SerializedName("imdbID")
    private String imdbID = null;

    @SerializedName("seriesID")
    private String seriesID = null;

    @SerializedName("Type")
    private String type = null;

    @SerializedName("totalSeasons")
    private Integer totalSeasons = null;

    @SerializedName("Episodes")
    private List<EpisodeData> episodes = null;

    @SerializedName("Search")
    private List<SearchItem> search = null;

    @SerializedName("totalResults")
    private Integer totalResults = null;

    public ModelApiResponse response(Boolean response) {
        this.response = response;
        return this;
    }

    /**
     * Get response
     *
     * @return response
     **/
    @ApiModelProperty(value = "")
    public Boolean isResponse() {
        return response;
    }

    public void setResponse(Boolean response) {
        this.response = response;
    }

    public ModelApiResponse error(String error) {
        this.error = error;
        return this;
    }

    /**
     * Get error
     *
     * @return error
     **/
    @ApiModelProperty(value = "")
    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public ModelApiResponse title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     **/
    @ApiModelProperty(value = "")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public ModelApiResponse year(String year) {
        this.year = year;
        return this;
    }

    /**
     * Get year
     *
     * @return year
     **/
    @ApiModelProperty(value = "")
    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public ModelApiResponse rated(String rated) {
        this.rated = rated;
        return this;
    }

    /**
     * Get rated
     *
     * @return rated
     **/
    @ApiModelProperty(value = "")
    public String getRated() {
        return rated;
    }

    public void setRated(String rated) {
        this.rated = rated;
    }

    public ModelApiResponse released(String released) {
        this.released = released;
        return this;
    }

    /**
     * Get released
     *
     * @return released
     **/
    @ApiModelProperty(value = "")
    public String getReleased() {
        return released;
    }

    public void setReleased(String released) {
        this.released = released;
    }

    public ModelApiResponse season(Integer season) {
        this.season = season;
        return this;
    }

    /**
     * Get season
     *
     * @return season
     **/
    @ApiModelProperty(value = "")
    public Integer getSeason() {
        return season;
    }

    public void setSeason(Integer season) {
        this.season = season;
    }

    public ModelApiResponse episode(Integer episode) {
        this.episode = episode;
        return this;
    }

    /**
     * Get episode
     *
     * @return episode
     **/
    @ApiModelProperty(value = "")
    public Integer getEpisode() {
        return episode;
    }

    public void setEpisode(Integer episode) {
        this.episode = episode;
    }

    public ModelApiResponse runtime(String runtime) {
        this.runtime = runtime;
        return this;
    }

    /**
     * Get runtime
     *
     * @return runtime
     **/
    @ApiModelProperty(value = "")
    public String getRuntime() {
        return runtime;
    }

    public void setRuntime(String runtime) {
        this.runtime = runtime;
    }

    public ModelApiResponse genre(String genre) {
        this.genre = genre;
        return this;
    }

    /**
     * Get genre
     *
     * @return genre
     **/
    @ApiModelProperty(value = "")
    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public ModelApiResponse director(String director) {
        this.director = director;
        return this;
    }

    /**
     * Get director
     *
     * @return director
     **/
    @ApiModelProperty(value = "")
    public String getDirector() {
        return director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    public ModelApiResponse writer(String writer) {
        this.writer = writer;
        return this;
    }

    /**
     * Get writer
     *
     * @return writer
     **/
    @ApiModelProperty(value = "")
    public String getWriter() {
        return writer;
    }

    public void setWriter(String writer) {
        this.writer = writer;
    }

    public ModelApiResponse actors(String actors) {
        this.actors = actors;
        return this;
    }

    /**
     * Get actors
     *
     * @return actors
     **/
    @ApiModelProperty(value = "")
    public String getActors() {
        return actors;
    }

    public void setActors(String actors) {
        this.actors = actors;
    }

    public ModelApiResponse plot(String plot) {
        this.plot = plot;
        return this;
    }

    /**
     * Get plot
     *
     * @return plot
     **/
    @ApiModelProperty(value = "")
    public String getPlot() {
        return plot;
    }

    public void setPlot(String plot) {
        this.plot = plot;
    }

    public ModelApiResponse language(String language) {
        this.language = language;
        return this;
    }

    /**
     * Get language
     *
     * @return language
     **/
    @ApiModelProperty(value = "")
    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public ModelApiResponse country(String country) {
        this.country = country;
        return this;
    }

    /**
     * Get country
     *
     * @return country
     **/
    @ApiModelProperty(value = "")
    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public ModelApiResponse awards(String awards) {
        this.awards = awards;
        return this;
    }

    /**
     * Get awards
     *
     * @return awards
     **/
    @ApiModelProperty(value = "")
    public String getAwards() {
        return awards;
    }

    public void setAwards(String awards) {
        this.awards = awards;
    }

    public ModelApiResponse poster(String poster) {
        this.poster = poster;
        return this;
    }

    /**
     * Get poster
     *
     * @return poster
     **/
    @ApiModelProperty(value = "")
    public String getPoster() {
        return poster;
    }

    public void setPoster(String poster) {
        this.poster = poster;
    }

    public ModelApiResponse ratings(List<RatingData> ratings) {
        this.ratings = ratings;
        return this;
    }

    public ModelApiResponse addRatingsItem(RatingData ratingsItem) {
        if (this.ratings == null) {
            this.ratings = new ArrayList<RatingData>();
        }
        this.ratings.add(ratingsItem);
        return this;
    }

    /**
     * Get ratings
     *
     * @return ratings
     **/
    @ApiModelProperty(value = "")
    public List<RatingData> getRatings() {
        return ratings;
    }

    public void setRatings(List<RatingData> ratings) {
        this.ratings = ratings;
    }

    public ModelApiResponse metascore(String metascore) {
        this.metascore = metascore;
        return this;
    }

    /**
     * Get metascore
     *
     * @return metascore
     **/
    @ApiModelProperty(value = "")
    public String getMetascore() {
        return metascore;
    }

    public void setMetascore(String metascore) {
        this.metascore = metascore;
    }

    public ModelApiResponse imdbRating(String imdbRating) {
        this.imdbRating = imdbRating;
        return this;
    }

    /**
     * Get imdbRating
     *
     * @return imdbRating
     **/
    @ApiModelProperty(value = "")
    public String getImdbRating() {
        return imdbRating;
    }

    public void setImdbRating(String imdbRating) {
        this.imdbRating = imdbRating;
    }

    public ModelApiResponse imdbVotes(String imdbVotes) {
        this.imdbVotes = imdbVotes;
        return this;
    }

    /**
     * Get imdbVotes
     *
     * @return imdbVotes
     **/
    @ApiModelProperty(value = "")
    public String getImdbVotes() {
        return imdbVotes;
    }

    public void setImdbVotes(String imdbVotes) {
        this.imdbVotes = imdbVotes;
    }

    public ModelApiResponse imdbID(String imdbID) {
        this.imdbID = imdbID;
        return this;
    }

    /**
     * Get imdbID
     *
     * @return imdbID
     **/
    @ApiModelProperty(value = "")
    public String getImdbID() {
        return imdbID;
    }

    public void setImdbID(String imdbID) {
        this.imdbID = imdbID;
    }

    public ModelApiResponse seriesID(String seriesID) {
        this.seriesID = seriesID;
        return this;
    }

    /**
     * Get seriesID
     *
     * @return seriesID
     **/
    @ApiModelProperty(value = "")
    public String getSeriesID() {
        return seriesID;
    }

    public void setSeriesID(String seriesID) {
        this.seriesID = seriesID;
    }

    public ModelApiResponse type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @ApiModelProperty(value = "")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public ModelApiResponse totalSeasons(Integer totalSeasons) {
        this.totalSeasons = totalSeasons;
        return this;
    }

    /**
     * Get totalSeasons
     *
     * @return totalSeasons
     **/
    @ApiModelProperty(value = "")
    public Integer getTotalSeasons() {
        return totalSeasons;
    }

    public void setTotalSeasons(Integer totalSeasons) {
        this.totalSeasons = totalSeasons;
    }

    public ModelApiResponse episodes(List<EpisodeData> episodes) {
        this.episodes = episodes;
        return this;
    }

    public ModelApiResponse addEpisodesItem(EpisodeData episodesItem) {
        if (this.episodes == null) {
            this.episodes = new ArrayList<EpisodeData>();
        }
        this.episodes.add(episodesItem);
        return this;
    }

    /**
     * Get episodes
     *
     * @return episodes
     **/
    @ApiModelProperty(value = "")
    public List<EpisodeData> getEpisodes() {
        return episodes;
    }

    public void setEpisodes(List<EpisodeData> episodes) {
        this.episodes = episodes;
    }

    public ModelApiResponse search(List<SearchItem> search) {
        this.search = search;
        return this;
    }

    public ModelApiResponse addSearchItem(SearchItem searchItem) {
        if (this.search == null) {
            this.search = new ArrayList<SearchItem>();
        }
        this.search.add(searchItem);
        return this;
    }

    /**
     * Get search
     *
     * @return search
     **/
    @ApiModelProperty(value = "")
    public List<SearchItem> getSearch() {
        return search;
    }

    public void setSearch(List<SearchItem> search) {
        this.search = search;
    }

    public ModelApiResponse totalResults(Integer totalResults) {
        this.totalResults = totalResults;
        return this;
    }

    /**
     * Get totalResults
     *
     * @return totalResults
     **/
    @ApiModelProperty(value = "")
    public Integer getTotalResults() {
        return totalResults;
    }

    public void setTotalResults(Integer totalResults) {
        this.totalResults = totalResults;
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ModelApiResponse {\n");

        sb.append("    response: ").append(toIndentedString(response)).append("\n");
        sb.append("    error: ").append(toIndentedString(error)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    year: ").append(toIndentedString(year)).append("\n");
        sb.append("    rated: ").append(toIndentedString(rated)).append("\n");
        sb.append("    released: ").append(toIndentedString(released)).append("\n");
        sb.append("    season: ").append(toIndentedString(season)).append("\n");
        sb.append("    episode: ").append(toIndentedString(episode)).append("\n");
        sb.append("    runtime: ").append(toIndentedString(runtime)).append("\n");
        sb.append("    genre: ").append(toIndentedString(genre)).append("\n");
        sb.append("    director: ").append(toIndentedString(director)).append("\n");
        sb.append("    writer: ").append(toIndentedString(writer)).append("\n");
        sb.append("    actors: ").append(toIndentedString(actors)).append("\n");
        sb.append("    plot: ").append(toIndentedString(plot)).append("\n");
        sb.append("    language: ").append(toIndentedString(language)).append("\n");
        sb.append("    country: ").append(toIndentedString(country)).append("\n");
        sb.append("    awards: ").append(toIndentedString(awards)).append("\n");
        sb.append("    poster: ").append(toIndentedString(poster)).append("\n");
        sb.append("    ratings: ").append(toIndentedString(ratings)).append("\n");
        sb.append("    metascore: ").append(toIndentedString(metascore)).append("\n");
        sb.append("    imdbRating: ").append(toIndentedString(imdbRating)).append("\n");
        sb.append("    imdbVotes: ").append(toIndentedString(imdbVotes)).append("\n");
        sb.append("    imdbID: ").append(toIndentedString(imdbID)).append("\n");
        sb.append("    seriesID: ").append(toIndentedString(seriesID)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    totalSeasons: ").append(toIndentedString(totalSeasons)).append("\n");
        sb.append("    episodes: ").append(toIndentedString(episodes)).append("\n");
        sb.append("    search: ").append(toIndentedString(search)).append("\n");
        sb.append("    totalResults: ").append(toIndentedString(totalResults)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

